FROM rust:1 AS chef

RUN rustup target add x86_64-pc-windows-gnu

# We only pay the installation cost once,
# it will be cached from the second build onwards
RUN cargo install cargo-chef

WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --bin squidhammer --recipe-path recipe.json

FROM chef AS builder

RUN apt-get update && apt-get install -y mingw-w64 && \
    rm -rf /var/cache/apt/archives && \
    rm -rf /var/lib/apt/lists/*

COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --bin squidhammer --release --target x86_64-pc-windows-gnu --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --release --target x86_64-pc-windows-gnu -p squidhammer

FROM scratch AS artifact
COPY --from=builder /app/target/x86_64-pc-windows-gnu/release/squidhammer.* /